name: Badges

on: push

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Get the Numbers
        run: |
          echo "ANSWER=14" >> $GITHUB_ENV
          echo "SECOND=90" >> $GITHUB_ENV
      - name: Set color
        id: set_color
        run: |
          if [ ${{env.ANSWER}} -eq 0 ]
          then
            echo "::set-output name=color::grey"
          elif [ ${{env.ANSWER}} -le 20 ]
          then
            echo "::set-output name=color::red"
          elif [ ${{env.ANSWER}} -le 40 ]
          then
             echo "::set-output name=color::orange"
          elif [ ${{env.ANSWER}} -le 60 ]
          then
             echo "::set-output name=color::yellow"
          elif [ ${{env.ANSWER}} -le 80 ]
          then
             echo "::set-output name=color::yellowgreen" 
          elif [ ${{env.ANSWER}} -gt 80 ]
          then
             echo "::set-output name=color::success"   
           fi  
      - name: Log rate-limit before 
        run: curl -I https://api.github.com/users/itachi1994
        
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ef5e6c565f44ad0553266659a03c2793
          filename: answer.json
          label: ""
          message: ${{ env.ANSWER }}
          color: ${{steps.set_color.outputs.color}}
     
      - name: Log rate-limit after 
        run: curl -I https://api.github.com/users/itachi1994     
          
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ef5e6c565f44ad0553266659a03c2793
          filename: second.json
          label: second
          message: ${{ env.SECOND }}
          color: brightgreen   
