name: Badges

on: push

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Get the Numbers
        run: |
          echo "ANSWER=84" >> $GITHUB_ENV
          echo "SECOND=60" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ef5e6c565f44ad0553266659a03c2793
          filename: answer.json
          label: ""
          namedLogo: sharp
          logoColor: black
          message: ${{ env.ANSWER }}
          color: success
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ef5e6c565f44ad0553266659a03c2793
          filename: second.json
          label: second
          message: ${{ env.SECOND }}
          style: social
          color: brightgreen   
