name: Badges

on: push

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Get the Numbers
      run: echo "ANSWER=42" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <gist-ID>
          filename: answer.json
          label: The Answer is
          message: ${{ env.ANSWER }}
          color: green